config/routes.rb
def cavy_locale_scope
  (I18n.available_locales.count > 1) ? '(:locale)' : ''
end

Cavy::Engine.routes.draw do

  scope(cavy_locale_scope, locale: /#{I18n.available_locales.join('|')}/) do
    root to: 'pages#page'

    resources :users

    get '/first_time/welcome', to: 'first_time#welcome', as: 'cavy_first_time_welcome'
    get '/first_time/user', to: 'first_time#new_user', as: 'cavy_first_time_new_user'
    post '/first_time/user', to: 'first_time#create_user', as: 'cavy_first_time_create_user'

    get '/admin', to: 'admin#dashboard', as: 'admin_dashboard'

    post '/admin/page_templates/:id/field', to: 'admin_page_template_fields#create', as: 'admin_create_page_template_field'
    delete '/admin/page_templates/:id/delete_field/:field', to: 'admin_page_template_fields#delete', as: 'admin_delete_page_template_field'

    get '/admin/page_templates', to: 'admin_page_templates#index', as: 'admin_page_templates'
    get '/admin/page_template/new', to: 'admin_page_templates#new', as: 'admin_new_page_template'
    post '/admin/page_template', to: 'admin_page_templates#create', as: 'admin_create_page_template'
    get '/admin/page_template/:id', to: 'admin_page_templates#edit', as: 'admin_edit_page_template'
    patch '/admin/page_template/:id', to: 'admin_page_templates#update', as: 'admin_update_page_template'
    delete '/admin/page_template/:id', to: 'admin_page_templates#delete', as: 'admin_delete_page_template'


    get '/admin/pages', to: 'admin_pages#index', as: 'admin_pages'
    get '/admin/new_page', to: 'admin_pages#new', as: 'admin_new_page'
    post '/admin/page', to: 'admin_pages#create', as: 'admin_create_page'
    get '/admin/page/data/:id', to: 'admin_page_data#new', as: 'admin_add_page_data'
    post '/admin/page/data/:id', to: 'admin_page_data#create', as: 'admin_create_page_data'
    get '/admin/page/:id', to: 'admin_pages#edit', as: 'admin_edit_page'
    put '/admin/page/:id', to: 'admin_pages#update', as: 'admin_update_page'
    delete '/admin/page/:id', to: 'admin_pages#delete', as: 'admin_delete_page'

    get '/admin/sections', to: 'item_sections#index', as: 'cavy_item_sections'
    get '/admin/sections/new', to: 'item_sections#new', as: 'cavy_new_item_section'
    get '/admin/sections/edit/:id', to: 'item_sections#edit', as: 'cavy_edit_item_section'
    post '/admin/sections', to: 'item_sections#create', as: 'cavy_create_item_section'
    get '/admin/section/:id', to: 'item_sections#show', as: 'cavy_item_section'
    patch '/admin/section/:id', to: 'item_sections#update', as: 'cavy_update_item_section'
    delete '/admin/section/:id', to: 'item_sections#destroy', as: 'cavy_delete_item_section'

    get '/admin/item_group', to: 'item_groups#index', as: 'item_groups'
    get '/admin/item_group/new', to: 'item_groups#new', as: 'admin_new_item_group'
    get '/admin/item_group/edit/:id', to: 'item_groups#edit', as: 'admin_edit_item_group'
    post '/admin/item_group', to: 'item_groups#create', as: 'cavy_create_item_group'
    get '/admin/item_group/:id', to: 'item_groups#show', as: 'cavy_item_group'
    patch '/admin/item_group/:id', to: 'item_groups#update', as: 'cavy_update_item_group'
    delete '/admin/item_group/:id', to: 'item_groups#destroy', as: 'cavy_delete_item_group'
    post '/admin/item_group/order', to: 'item_groups#update_order', as: 'cavy_update_order_item_group'

    get '/admin/item/new/:group_id', to: 'items#new', as: 'cavy_new_item'
    post '/admin/item/new/:group_id', to: 'items#create', as: 'cavy_create_item'
    get '/admin/item/edit/:id', to: 'items#edit', as: 'cavy_edit_item'
    get '/admin/item/:id', to: 'items#show', as: 'cavy_item'
    patch '/admin/item/:id', to: 'items#update', as: 'cavy_update_item'
    delete '/admin/item/:id', to: 'items#destroy', as: 'cavy_delete_item'

    get '/admin/signin', to: 'sessions#new', as: 'admin_signin'
    post '/admin/signin', to: 'sessions#create', as: 'admin_create_session'
    get '/admin/signout', to: 'sessions#destroy', as: 'admin_destroy_session'

    get '/admin/new_user', to: 'users#new', as: 'cavy_admin_new_user'
    get '/admin/users', to: 'users#index', as: 'cavy_admin_users'

    get ':route', to: 'pages#page', as: 'cavy_page'
  end

end

app/models/cavy/application_record.rb
module Cavy
  class ApplicationRecord < ::ActiveRecord::Base

    self.abstract_class = true

  end
end

app/models/cavy/group.rb
module Cavy
  class Group < ::ActiveRecord::Base

    has_and_belongs_to_many :cavy_users, class_name: 'Cavy::User', foreign_key: 'cavy_group_id', association_foreign_key: 'cavy_user_id'
    has_and_belongs_to_many :cavy_policies, class_name: 'Cavy::Policy', foreign_key: 'cavy_group_id', association_foreign_key: 'cavy_policy_id'

  end
end

app/models/cavy/item.rb
module Cavy
  class Item < ::ActiveRecord::Base

    belongs_to :cavy_item_group

    def create_params(type, params)
      data = {}
      data['type'] = type
      params.try(:each) do |param|
        data["#{param.downcase.gsub(' ', '_')}".to_sym] = ''
      end
      self.data = data
    end

  end
end

app/models/cavy/item_group.rb
module Cavy
  class ItemGroup < ::ActiveRecord::Base

    attr_accessor :param_string

    has_many :cavy_items

    before_save :set_params
    validates :title, presence: true

    def type
      title.downcase.gsub(' ', '_')
    end

    def items
      Cavy::Item.where(item_group_id: id)
    end

    def items_with_key_value(key, value)
      item_group = Cavy::ItemGroup.find(id)
      item_group.items.where("data.#{key}" => value)
    end

    private

    def set_params
      unless param_string == '' or param_string == nil
        self.params = param_string.gsub(/[,][ ]*/, ',').split(',')
      end
    end

  end
end

app/models/cavy/item_section.rb
module Cavy
  class ItemSection < ::ActiveRecord::Base

    validates :title, presence: true, uniqueness: true

  end
end

app/models/cavy/page.rb
module Cavy
  class Page < ::ActiveRecord::Base

    validates :route, uniqueness: true

    attr_accessor :tag_string, :key, :value
    attr_accessor :seo_description_string, :key, :value
    belongs_to :cavy_page_template, class_name: 'Cavy::PageTemplate'

    %i[make_route check_tags check_page_elements update_render].each do |method|
      before_save method
      before_create method
    end

    def localized_title (locale = nil)
      locale ||= I18n.locale.to_s
      text = self.title[locale.to_s]

      if text.to_s == '' and locale != Cavy.default_locale.to_s
        text = self.title[Cavy.default_locale.to_s]
      end

      Cavy.locales.try(:each) do |alt_locale|
        unless alt_locale.to_s == Cavy.default_locale.to_s or alt_locale.to_s == locale
          text = self.title[alt_locale.to_s]
        end
        break if text.to_s != ''
      end if text.to_s == ''
      text.to_s
    end

    def set_title (new_title, locale=nil)
      locale ||= I18n.locale.to_s

      self.title[locale] = new_title
    end

    def update_page (params, locale)
      self.title = params[:title] if params[:title].to_h != {}
      self.update_elements(params[:page_elements].to_h, locale)
      self.update_attributes(params.except(:title, :page_elements))
    end

    def set_content (new_content)
      self.content[I18n.locale.to_s] = new_content
    end

    def get_page_element(element, locale=nil)
      locale ||= I18n.locale.to_s
      text = localized_page_element(element, locale)

      if text.to_s == '' and locale != Cavy.default_locale.to_s
        text = localized_page_element(element, Cavy.default_locale)
      end

      Cavy.locales.try(:each) do |alt_locale|
        unless alt_locale.to_s == Cavy.default_locale.to_s or alt_locale.to_s == locale
          text = localized_page_element(element, alt_locale)
        end
        break if text.to_s != ''
      end if text.to_s == ''

      text.to_s
    end

    def get_title_translations
      translations = {}
      Cavy.locales.try(:each) do |alt_locale|
        translations[alt_locale] = self.title[alt_locale.to_s].to_s
      end
      translations
    end

    def get_translations (element)
      translations = {}
      Cavy.locales.try(:each) do |alt_locale|
        translations[alt_locale] = localized_page_element(element, alt_locale)
      end
      translations
    end

    def update_elements(params, locale = nil)
      locale ||= I18n.locale.to_s
      update_values = {page_elements: {}}

      self.page_elements.try(:each) do |key, value|
        update_values[:page_elements][key] = value
      end

      params.try(:each) do |key, value|
        locales = (value.is_a?(Hash)) ? Cavy.locales.collect {|alt_locale| alt_locale.to_s} : [locale]
        locales.try(:each) do |alt_locale|
          localized_key, localized_value = parse_page_element key, value, alt_locale
          update_values[:page_elements][localized_key] = localized_value unless localized_value.nil?
        end
      end

      self.update(update_values) if update_values != {}
    end

    def set_key_value(key, value)
      self.data = {} if self.data == nil
      self.data[key] = value
    end

    private

    def parse_page_element (key, value, locale)
      localized_key = key.to_s + '_' + locale
      localized_value = (value.is_a? Hash) ? value[locale.to_sym] : value
      unless self.cavy_page_template.nil?
        picture_fields = self.cavy_page_template.fields.collect {|field_key, field_value| (field_value == 'PICTURE') ? field_key : nil}.compact
        localized_value = upload_image localized_value if picture_fields.include? key
      end
      return localized_key, localized_value
    end

    def localized_page_element (element, locale)
      self.page_elements[element + '_' + locale.to_s].to_s
    end

    def upload_image (picture)
      return '' if picture.nil?
      uploader = Cavy.uploader || Cavy::FileUploader.new
      uploader.store!(picture)
      url = uploader.url
      Cavy::Resource.find_or_create_by(name: picture.original_filename, url: url, file_type: 'IMAGE')
      url
    end

    def check_page_elements
      self.page_elements = {} if self.page_elements == nil
    end

    def check_tags
      self.seo_keywords = {} if self.seo_keywords.nil?
      self.seo_description = {} if self.seo_description.nil?

      self.seo_keywords[I18n.locale.to_s] = tag_string.split(',') unless tag_string.to_s == ''
      self.seo_description[I18n.locale.to_s] = seo_description_string unless seo_description_string.to_s == ''
    end

    def make_route
      self.route = localized_title.tr(' ', '_').downcase if route.to_s == ''
    end

    def update_render
      unless self.cavy_page_template_id.nil?
        template = Cavy::PageTemplate.find(self.cavy_page_template_id)
        self.render = template.template unless template.nil?
      end
    end

  end
end

app/models/cavy/page_template.rb
module Cavy
  class PageTemplate < ApplicationRecord

    @options = [
        {name: 'string', type: 'STRING'},
        {name: 'text', type: 'TEXT'},
        {name: 'picture', type: 'PICTURE'},
    ]

    def self.get_field_options_for_select
      @options.map { |o| [o[:name], o[:type]] }
    end

    def add_field(field, type)
      self.fields ||= {}
      fields[field] = type
      save
    end

    def remove_field(field)
      self.fields ||= {}
      fields.delete field
      save
    end

  end
end

app/models/cavy/permissions.rb
module Cavy
  module Permissions

    def self.permission_for(user)
      if user == nil
        GuestPermission.new
      elsif user.role == 'admin'
        AdminPermission.new(user)
      elsif user.role == 'developer'
        DeveloperPermission.new(user)
      elsif user.role == 'designer'
        DesignerPermission.new(user)
      elsif user.role == 'client'
        ClientPermission.new(user)
      end
    end

  end
end

app/models/cavy/permissions/admin_permission.rb
module Cavy
  module Permissions
    class AdminPermission < BasePermission

      def initialize(user)
        allow_all
      end

    end
  end
end

app/models/cavy/permissions/base_permission.rb
module Cavy
  module Permissions
    class BasePermission

      def allow?(controller, action, resource = nil)
        allowed = @allow_all || @allowed_actions[[controller.to_s, action.to_s]]
        allowed && (allowed == true || resource && allowed.call(resource))
      end

      def allow_all
        @allow_all = true
      end

      def allow(controllers, actions)
        @allowed_actions ||= {}
        Array(controllers).each do |controller|
          Array(actions).each do |action|
            @allowed_actions[[controller.to_s, action.to_s]] = true
          end
        end
      end

      def allow_param(resources, attributes)
        @allowed_params ||= {}
        Array(resources).each do |resource|
          @allowed_params[resource] ||= []
          @allowed_params[resource] += Array(attributes)
        end
      end

      def allow_param?(resource, attribute)
        if @allow_all
          true
        elsif @allowed_params && @allowed_params[resource]
          @allowed_params[resource].include? attribute
        end
      end

      def permit_params!(params)
        if @allow_all
          params.permit!
        elsif @allowed_params
          @allowed_params.each do |resource, attributes|
            if params[resource].respond_to? :permit
              hstore_data      = get_hstore_data(attributes, params[resource])
              params[resource] = params[resource].permit(*attributes)
              params[resource].merge!(hstore_data)
              params.permit!
            end
          end
        end
      end

      private

      def get_hstore_data(attributes, resource)
        hstore_data = {}
        attributes.each do |attribute|
          if attribute.class == Hash and resource[attribute.keys.first]
            hstore_data[attribute.keys.first] = resource[attribute.keys.first]
          end
        end
        hstore_data
      end

    end
  end
end

app/models/cavy/permissions/client_permission.rb
module Cavy
  module Permissions
    class ClientPermission < BasePermission

      def initialize(user)
        allow 'cavy/sessions', [:new, :create, :destroy]

        allow 'cavy/pages', [:page, :edit, :update]
        allow 'cavy/admin', [:dashboard, :users, :new_user]
        allow 'cavy/admin_pages', [:index, :show, :update, :edit, :add_data, :create_data]
        allow 'cavy/mercury', [:edit, :resource, :snippet_options, :snippet_preview, :test_page, :image]
        allow 'cavy/users', [:index, :show, :edit, :update, :new, :create]
        allow 'cavy/item_groups', [:index, :show, :edit, :update, :update_order]
        allow 'cavy/items', [:index, :show, :new, :edit, :create, :update, :destroy]
        allow 'cavy/item_sections', [:index, :show]
        allow 'cavy/statistics', [:visitor_history, :page_view_history]
        allow_param :page, [:title, :description, :tag_string, :key, :value, data: :hstore]
        allow_param :item, [data: :hstore]
      end

    end
  end
end

app/models/cavy/permissions/designer_permission.rb
module Cavy
  module Permissions
    class DesignerPermission < BasePermission

      def initialize(user)
        allow_all
      end

    end
  end
end

app/models/cavy/permissions/developer_permission.rb
module Cavy
  module Permissions
    class DeveloperPermission < BasePermission

      def initialize(user)
        allow_all
      end

    end
  end
end

app/models/cavy/permissions/guest_permission.rb
module Cavy
  module Permissions
    class GuestPermission < BasePermission

      def initialize
        allow 'cavy/pages', [:page]
        allow 'cavy/sessions', [:new, :create, :destroy]
        allow 'cavy/first_time', [:welcome, :new_user, :create_user]
      end

    end
  end
end

app/models/cavy/resource.rb
module Cavy
  class Resource < ApplicationRecord
  end
end

app/controllers/cavy/admin_controller.rb
require_dependency 'cavy/application_controller'

module Cavy
  class AdminController < ApplicationController

    layout 'cavy/admin_layout'

    def dashboard
      @users = Cavy::User.all
      @pages = Cavy::Page.all
    end

  end
end

app/controllers/cavy/admin_page_data_controller.rb
require_dependency 'cavy/application_controller'

module Cavy
  class AdminPageDataController < ApplicationController

    layout 'cavy/admin_layout'

    def new
      @page = Cavy::Page.find(params[:id])
      render 'cavy/admin_pages/data/new'
    end

    def create
      @page = Cavy::Page.find(params[:id])
      @page.set_key_value(params[:page][:key], params[:page][:value])
      if @page.save
        redirect_to admin_edit_page_path(@page.id), flash: {success: 'Successfully updated page.'}
      else
        render action :new
      end
    end

    private

    def page_params
      # TODO Find a way to use hstore with strong parameters
      # params.require(:page).permit(:title, :render, :route, :tag_string, :description, :key, :value, :data)
    end

  end
end

app/controllers/cavy/admin_page_template_fields_controller.rb
require_dependency 'cavy/application_controller'

module Cavy
  class AdminPageTemplateFieldsController < ApplicationController

    layout 'cavy/admin_layout'

    def create
      field_params   = page_template_params
      @page_template = Cavy::PageTemplate.find(params[:id])
      @page_template.add_field(field_params[:name], field_params[:type])

      redirect_to admin_edit_page_template_path(@page_template.id), flash: {success: 'Page template fields were successfully updated.'}
    end

    def delete
      @page_template = Cavy::PageTemplate.find(params[:id])
      @page_template.remove_field(params[:field])

      redirect_to admin_edit_page_template_path(@page_template.id), flash: {ssuccess: 'Page Template field was deleted.'}
    end

    private

    def page_template_params
      params.require(:page_template).permit(:name, :type)
    end

  end
end

app/views/cavy/admin_page_templates/_form.html.erb
<% if params[:action] == 'new' or params[:action] == 'create' %>
    <% url = admin_create_page_template_path %>
    <% method = 'post' %>
    <% submit_text = 'Create' %>
<% else %>
    <% url = admin_update_page_template_path(@page_template.id) %>
    <% method = 'patch' %>
    <% submit_text = 'Update' %>
<% end %>

<div class="row">
  <div class="large-12 columns">
    <%= form_for @page_template, url: url, method: method do |f| %>
        <% if @page_template.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= "#{pluralize(@page_template.errors.count, "error")} prohibited this page template from being saved:" %>
              </h2>
              <ul>
                <% @page_template.errors.full_messages.each do |msg| %>
                    <li>
                      <%= msg %>
                    </li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :template, class: 'control-label' %>
        <%= f.text_field :template, class: 'form-control' %>
        <%= f.submit submit_text, class: 'button small success', id: 'add' %>
    <% end %>
  </div>
</div>

app/views/cavy/admin_page_templates/edit.html.erb
<div class="page-header">
  <h1>Page Template: <%= @page_template.name %></h1>
</div>

<div class="expanded row">
  <div class="large-9 columns">
    <div class="form-set">

      <div class="form-set-title">
        Fields:
      </div>

      <% if @page_template.fields.nil? || @page_template.fields.empty? %>
          There are no page template fields set yet.
      <% else %>
          <table>
            <thead>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th></th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @page_template.fields.each do |name, value| %>
                <tr>

                  <td><%= name %></td>
                  <td><%= value %></td>
                  <td>
                    <%= form_tag admin_create_page_template_field_path(@page_template.id), method: :post do %>
                        <%= hidden_field_tag 'page_template[name]', name %>
                        <div class="row">
                          <div class="large-6 columns">
                            <%= select_tag 'page_template[type]', options_for_select(Cavy::PageTemplate.get_field_options_for_select, value), id: "type-#{name}" %>
                          </div>
                          <div class="large-4 columns">
                            <%= submit_tag 'Update', class: 'button small success', id: "submit-#{name}" %>
                          </div>
                        </div>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to 'Destroy', admin_delete_page_template_field_path(@page_template.id, name), class: 'button small alert', method: :delete, data: {:confirm => 'Are you sure?'}, id: "delete-#{@page_template.id}-#{name}" %>
                  </td>
                </tr>
            <% end %>

            </tbody>
          </table>
      <% end %>
    </div>
    <div class="form-set">

      <div class="form-set-title">
        Add Field:
      </div>
      <%= form_tag admin_create_page_template_field_path(@page_template.id), method: :post do %>
          <div class="row">
            <div class="large-9 columns">
              <%= label_tag :name %>
              <%= text_field_tag 'page_template[name]', nil, id: :name %>
            </div>
            <div class="large-3 columns">
              <%= label_tag :type %>
              <%= select_tag 'page_template[type]', options_for_select(Cavy::PageTemplate.get_field_options_for_select), id: :type %>
            </div>
          </div>

          <%= submit_tag 'Add', class: 'button small success', id: 'submit' %>
      <% end %>
    </div>
  </div>

  <div class="large-3 columns">
    <div class="form-set">
      <div class="form-set-title">
        Settings:
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cavy/admin_page_templates/index.html.erb
<div class="page-header" id="with-button">
  <h1>Page Templates</h1>
  <a class="button primary small" href="<%= admin_new_page_template_path %>" id="admin-new-page-template">New Page
    Template</a>
</div>

<br/>

<% if @page_templates.count >= 1 %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Template to Render</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @page_templates.each do |page_template| %>
          <tr>
            <td>
              <%= link_to page_template.name, admin_edit_page_template_path(page_template.id), id: "edit-page-template-#{page_template.id}" %>
            </td>
            <td>
              <%= page_template.template %>
            </td>
            <% if current_user.dev_team? %>
                <td>
                  <%= link_to 'Destroy', admin_delete_page_template_path(page_template.id), class: 'button small alert', method: :delete, data: {confirm: 'Are you sure?'}, id: "delete-page-template-#{page_template.id}" %>
                </td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    You dont have any page templates yet.
<% end %>

app/views/cavy/admin_page_templates/new.html.erb
<div class="page-header">
  <h1>New Page Template</h1>
</div>

<%= render 'form' %>