config/routes.rb
def cavy_locale_scope
  (I18n.available_locales.count > 1) ? '(:locale)' : ''
end

Cavy::Engine.routes.draw do

  scope(cavy_locale_scope, locale: /#{I18n.available_locales.join('|')}/) do
    root to: 'pages#page'

    resources :users

    get '/first_time/welcome', to: 'first_time#welcome', as: 'cavy_first_time_welcome'
    get '/first_time/user', to: 'first_time#new_user', as: 'cavy_first_time_new_user'
    post '/first_time/user', to: 'first_time#create_user', as: 'cavy_first_time_create_user'

    get '/admin', to: 'admin#dashboard', as: 'admin_dashboard'

    post '/admin/page_templates/:id/field', to: 'admin_page_template_fields#create', as: 'admin_create_page_template_field'
    delete '/admin/page_templates/:id/delete_field/:field', to: 'admin_page_template_fields#delete', as: 'admin_delete_page_template_field'

    get '/admin/page_templates', to: 'admin_page_templates#index', as: 'admin_page_templates'
    get '/admin/page_template/new', to: 'admin_page_templates#new', as: 'admin_new_page_template'
    post '/admin/page_template', to: 'admin_page_templates#create', as: 'admin_create_page_template'
    get '/admin/page_template/:id', to: 'admin_page_templates#edit', as: 'admin_edit_page_template'
    patch '/admin/page_template/:id', to: 'admin_page_templates#update', as: 'admin_update_page_template'
    delete '/admin/page_template/:id', to: 'admin_page_templates#delete', as: 'admin_delete_page_template'


    get '/admin/pages', to: 'admin_pages#index', as: 'admin_pages'
    get '/admin/new_page', to: 'admin_pages#new', as: 'admin_new_page'
    post '/admin/page', to: 'admin_pages#create', as: 'admin_create_page'
    get '/admin/page/data/:id', to: 'admin_page_data#new', as: 'admin_add_page_data'
    post '/admin/page/data/:id', to: 'admin_page_data#create', as: 'admin_create_page_data'
    get '/admin/page/:id', to: 'admin_pages#edit', as: 'admin_edit_page'
    put '/admin/page/:id', to: 'admin_pages#update', as: 'admin_update_page'
    delete '/admin/page/:id', to: 'admin_pages#delete', as: 'admin_delete_page'

    get '/admin/sections', to: 'item_sections#index', as: 'cavy_item_sections'
    get '/admin/sections/new', to: 'item_sections#new', as: 'cavy_new_item_section'
    get '/admin/sections/edit/:id', to: 'item_sections#edit', as: 'cavy_edit_item_section'
    post '/admin/sections', to: 'item_sections#create', as: 'cavy_create_item_section'
    get '/admin/section/:id', to: 'item_sections#show', as: 'cavy_item_section'
    patch '/admin/section/:id', to: 'item_sections#update', as: 'cavy_update_item_section'
    delete '/admin/section/:id', to: 'item_sections#destroy', as: 'cavy_delete_item_section'

    get '/admin/item_group', to: 'item_groups#index', as: 'item_groups'
    get '/admin/item_group/new', to: 'item_groups#new', as: 'admin_new_item_group'
    get '/admin/item_group/edit/:id', to: 'item_groups#edit', as: 'admin_edit_item_group'
    post '/admin/item_group', to: 'item_groups#create', as: 'cavy_create_item_group'
    get '/admin/item_group/:id', to: 'item_groups#show', as: 'cavy_item_group'
    patch '/admin/item_group/:id', to: 'item_groups#update', as: 'cavy_update_item_group'
    delete '/admin/item_group/:id', to: 'item_groups#destroy', as: 'cavy_delete_item_group'
    post '/admin/item_group/order', to: 'item_groups#update_order', as: 'cavy_update_order_item_group'

    get '/admin/item/new/:group_id', to: 'items#new', as: 'cavy_new_item'
    post '/admin/item/new/:group_id', to: 'items#create', as: 'cavy_create_item'
    get '/admin/item/edit/:id', to: 'items#edit', as: 'cavy_edit_item'
    get '/admin/item/:id', to: 'items#show', as: 'cavy_item'
    patch '/admin/item/:id', to: 'items#update', as: 'cavy_update_item'
    delete '/admin/item/:id', to: 'items#destroy', as: 'cavy_delete_item'

    get '/admin/signin', to: 'sessions#new', as: 'admin_signin'
    post '/admin/signin', to: 'sessions#create', as: 'admin_create_session'
    get '/admin/signout', to: 'sessions#destroy', as: 'admin_destroy_session'

    get '/admin/new_user', to: 'users#new', as: 'cavy_admin_new_user'
    get '/admin/users', to: 'users#index', as: 'cavy_admin_users'

    get ':route', to: 'pages#page', as: 'cavy_page'
  end

end

app/models/cavy/application_record.rb
module Cavy
  class ApplicationRecord < ::ActiveRecord::Base

    self.abstract_class = true

  end
end

app/models/cavy/group.rb
module Cavy
  class Group < ::ActiveRecord::Base

    has_and_belongs_to_many :cavy_users, class_name: 'Cavy::User', foreign_key: 'cavy_group_id', association_foreign_key: 'cavy_user_id'
    has_and_belongs_to_many :cavy_policies, class_name: 'Cavy::Policy', foreign_key: 'cavy_group_id', association_foreign_key: 'cavy_policy_id'

  end
end

app/models/cavy/item.rb
module Cavy
  class Item < ::ActiveRecord::Base

    belongs_to :cavy_item_group

    def create_params(type, params)
      data = {}
      data['type'] = type
      params.try(:each) do |param|
        data["#{param.downcase.gsub(' ', '_')}".to_sym] = ''
      end
      self.data = data
    end

  end
end

app/models/cavy/item_group.rb
module Cavy
  class ItemGroup < ::ActiveRecord::Base

    attr_accessor :param_string

    has_many :cavy_items

    before_save :set_params
    validates :title, presence: true

    def type
      title.downcase.gsub(' ', '_')
    end

    def items
      Cavy::Item.where(item_group_id: id)
    end

    def items_with_key_value(key, value)
      item_group = Cavy::ItemGroup.find(id)
      item_group.items.where("data.#{key}" => value)
    end

    private

    def set_params
      unless param_string == '' or param_string == nil
        self.params = param_string.gsub(/[,][ ]*/, ',').split(',')
      end
    end

  end
end

app/models/cavy/item_section.rb
module Cavy
  class ItemSection < ::ActiveRecord::Base

    validates :title, presence: true, uniqueness: true

  end
end

app/models/cavy/page.rb
module Cavy
  class Page < ::ActiveRecord::Base

    validates :route, uniqueness: true

    attr_accessor :tag_string, :key, :value
    attr_accessor :seo_description_string, :key, :value
    belongs_to :cavy_page_template, class_name: 'Cavy::PageTemplate'

    %i[make_route check_tags check_page_elements update_render].each do |method|
      before_save method
      before_create method
    end

    def localized_title (locale = nil)
      locale ||= I18n.locale.to_s
      text = self.title[locale.to_s]

      if text.to_s == '' and locale != Cavy.default_locale.to_s
        text = self.title[Cavy.default_locale.to_s]
      end

      Cavy.locales.try(:each) do |alt_locale|
        unless alt_locale.to_s == Cavy.default_locale.to_s or alt_locale.to_s == locale
          text = self.title[alt_locale.to_s]
        end
        break if text.to_s != ''
      end if text.to_s == ''
      text.to_s
    end

    def set_title (new_title, locale=nil)
      locale ||= I18n.locale.to_s

      self.title[locale] = new_title
    end

    def update_page (params, locale)
      self.title = params[:title] if params[:title].to_h != {}
      self.update_elements(params[:page_elements].to_h, locale)
      self.update_attributes(params.except(:title, :page_elements))
    end

    def set_content (new_content)
      self.content[I18n.locale.to_s] = new_content
    end

    def get_page_element(element, locale=nil)
      locale ||= I18n.locale.to_s
      text = localized_page_element(element, locale)

      if text.to_s == '' and locale != Cavy.default_locale.to_s
        text = localized_page_element(element, Cavy.default_locale)
      end

      Cavy.locales.try(:each) do |alt_locale|
        unless alt_locale.to_s == Cavy.default_locale.to_s or alt_locale.to_s == locale
          text = localized_page_element(element, alt_locale)
        end
        break if text.to_s != ''
      end if text.to_s == ''

      text.to_s
    end

    def get_title_translations
      translations = {}
      Cavy.locales.try(:each) do |alt_locale|
        translations[alt_locale] = self.title[alt_locale.to_s].to_s
      end
      translations
    end

    def get_translations (element)
      translations = {}
      Cavy.locales.try(:each) do |alt_locale|
        translations[alt_locale] = localized_page_element(element, alt_locale)
      end
      translations
    end

    def update_elements(params, locale = nil)
      locale ||= I18n.locale.to_s
      update_values = {page_elements: {}}

      self.page_elements.try(:each) do |key, value|
        update_values[:page_elements][key] = value
      end

      params.try(:each) do |key, value|
        locales = (value.is_a?(Hash)) ? Cavy.locales.collect {|alt_locale| alt_locale.to_s} : [locale]
        locales.try(:each) do |alt_locale|
          localized_key, localized_value = parse_page_element key, value, alt_locale
          update_values[:page_elements][localized_key] = localized_value unless localized_value.nil?
        end
      end

      self.update(update_values) if update_values != {}
    end

    def set_key_value(key, value)
      self.data = {} if self.data == nil
      self.data[key] = value
    end

    private

    def parse_page_element (key, value, locale)
      localized_key = key.to_s + '_' + locale
      localized_value = (value.is_a? Hash) ? value[locale.to_sym] : value
      unless self.cavy_page_template.nil?
        picture_fields = self.cavy_page_template.fields.collect {|field_key, field_value| (field_value == 'PICTURE') ? field_key : nil}.compact
        localized_value = upload_image localized_value if picture_fields.include? key
      end
      return localized_key, localized_value
    end

    def localized_page_element (element, locale)
      self.page_elements[element + '_' + locale.to_s].to_s
    end

    def upload_image (picture)
      return '' if picture.nil?
      uploader = Cavy.uploader || Cavy::FileUploader.new
      uploader.store!(picture)
      url = uploader.url
      Cavy::Resource.find_or_create_by(name: picture.original_filename, url: url, file_type: 'IMAGE')
      url
    end

    def check_page_elements
      self.page_elements = {} if self.page_elements == nil
    end

    def check_tags
      self.seo_keywords = {} if self.seo_keywords.nil?
      self.seo_description = {} if self.seo_description.nil?

      self.seo_keywords[I18n.locale.to_s] = tag_string.split(',') unless tag_string.to_s == ''
      self.seo_description[I18n.locale.to_s] = seo_description_string unless seo_description_string.to_s == ''
    end

    def make_route
      self.route = localized_title.tr(' ', '_').downcase if route.to_s == ''
    end

    def update_render
      unless self.cavy_page_template_id.nil?
        template = Cavy::PageTemplate.find(self.cavy_page_template_id)
        self.render = template.template unless template.nil?
      end
    end

  end
end

app/models/cavy/page_template.rb
module Cavy
  class PageTemplate < ApplicationRecord

    @options = [
        {name: 'string', type: 'STRING'},
        {name: 'text', type: 'TEXT'},
        {name: 'picture', type: 'PICTURE'},
    ]

    def self.get_field_options_for_select
      @options.map { |o| [o[:name], o[:type]] }
    end

    def add_field(field, type)
      self.fields ||= {}
      fields[field] = type
      save
    end

    def remove_field(field)
      self.fields ||= {}
      fields.delete field
      save
    end

  end
end

app/models/cavy/permissions.rb
module Cavy
  module Permissions

    def self.permission_for(user)
      if user == nil
        GuestPermission.new
      elsif user.role == 'admin'
        AdminPermission.new(user)
      elsif user.role == 'developer'
        DeveloperPermission.new(user)
      elsif user.role == 'designer'
        DesignerPermission.new(user)
      elsif user.role == 'client'
        ClientPermission.new(user)
      end
    end

  end
end

app/models/cavy/permissions/admin_permission.rb
module Cavy
  module Permissions
    class AdminPermission < BasePermission

      def initialize(user)
        allow_all
      end

    end
  end
end

app/models/cavy/permissions/base_permission.rb
module Cavy
  module Permissions
    class BasePermission

      def allow?(controller, action, resource = nil)
        allowed = @allow_all || @allowed_actions[[controller.to_s, action.to_s]]
        allowed && (allowed == true || resource && allowed.call(resource))
      end

      def allow_all
        @allow_all = true
      end

      def allow(controllers, actions)
        @allowed_actions ||= {}
        Array(controllers).each do |controller|
          Array(actions).each do |action|
            @allowed_actions[[controller.to_s, action.to_s]] = true
          end
        end
      end

      def allow_param(resources, attributes)
        @allowed_params ||= {}
        Array(resources).each do |resource|
          @allowed_params[resource] ||= []
          @allowed_params[resource] += Array(attributes)
        end
      end

      def allow_param?(resource, attribute)
        if @allow_all
          true
        elsif @allowed_params && @allowed_params[resource]
          @allowed_params[resource].include? attribute
        end
      end

      def permit_params!(params)
        if @allow_all
          params.permit!
        elsif @allowed_params
          @allowed_params.each do |resource, attributes|
            if params[resource].respond_to? :permit
              hstore_data      = get_hstore_data(attributes, params[resource])
              params[resource] = params[resource].permit(*attributes)
              params[resource].merge!(hstore_data)
              params.permit!
            end
          end
        end
      end

      private

      def get_hstore_data(attributes, resource)
        hstore_data = {}
        attributes.each do |attribute|
          if attribute.class == Hash and resource[attribute.keys.first]
            hstore_data[attribute.keys.first] = resource[attribute.keys.first]
          end
        end
        hstore_data
      end

    end
  end
end

app/models/cavy/permissions/client_permission.rb
module Cavy
  module Permissions
    class ClientPermission < BasePermission

      def initialize(user)
        allow 'cavy/sessions', [:new, :create, :destroy]

        allow 'cavy/pages', [:page, :edit, :update]
        allow 'cavy/admin', [:dashboard, :users, :new_user]
        allow 'cavy/admin_pages', [:index, :show, :update, :edit, :add_data, :create_data]
        allow 'cavy/mercury', [:edit, :resource, :snippet_options, :snippet_preview, :test_page, :image]
        allow 'cavy/users', [:index, :show, :edit, :update, :new, :create]
        allow 'cavy/item_groups', [:index, :show, :edit, :update, :update_order]
        allow 'cavy/items', [:index, :show, :new, :edit, :create, :update, :destroy]
        allow 'cavy/item_sections', [:index, :show]
        allow 'cavy/statistics', [:visitor_history, :page_view_history]
        allow_param :page, [:title, :description, :tag_string, :key, :value, data: :hstore]
        allow_param :item, [data: :hstore]
      end

    end
  end
end

app/models/cavy/permissions/designer_permission.rb
module Cavy
  module Permissions
    class DesignerPermission < BasePermission

      def initialize(user)
        allow_all
      end

    end
  end
end

app/models/cavy/permissions/developer_permission.rb
module Cavy
  module Permissions
    class DeveloperPermission < BasePermission

      def initialize(user)
        allow_all
      end

    end
  end
end

app/models/cavy/permissions/guest_permission.rb
module Cavy
  module Permissions
    class GuestPermission < BasePermission

      def initialize
        allow 'cavy/pages', [:page]
        allow 'cavy/sessions', [:new, :create, :destroy]
        allow 'cavy/first_time', [:welcome, :new_user, :create_user]
      end

    end
  end
end

app/models/cavy/resource.rb
module Cavy
  class Resource < ApplicationRecord
  end
end

app/controllers/cavy/admin_controller.rb
require_dependency 'cavy/application_controller'

module Cavy
  class AdminController < ApplicationController

    layout 'cavy/admin_layout'

    def dashboard
      @users = Cavy::User.all
      @pages = Cavy::Page.all
    end

  end
end

app/controllers/cavy/admin_page_data_controller.rb
require_dependency 'cavy/application_controller'

module Cavy
  class AdminPageDataController < ApplicationController

    layout 'cavy/admin_layout'

    def new
      @page = Cavy::Page.find(params[:id])
      render 'cavy/admin_pages/data/new'
    end

    def create
      @page = Cavy::Page.find(params[:id])
      @page.set_key_value(params[:page][:key], params[:page][:value])
      if @page.save
        redirect_to admin_edit_page_path(@page.id), flash: {success: 'Successfully updated page.'}
      else
        render action :new
      end
    end

    private

    def page_params
      # TODO Find a way to use hstore with strong parameters
      # params.require(:page).permit(:title, :render, :route, :tag_string, :description, :key, :value, :data)
    end

  end
end

app/controllers/cavy/admin_page_template_fields_controller.rb
require_dependency 'cavy/application_controller'

module Cavy
  class AdminPageTemplateFieldsController < ApplicationController

    layout 'cavy/admin_layout'

    def create
      field_params   = page_template_params
      @page_template = Cavy::PageTemplate.find(params[:id])
      @page_template.add_field(field_params[:name], field_params[:type])

      redirect_to admin_edit_page_template_path(@page_template.id), flash: {success: 'Page template fields were successfully updated.'}
    end

    def delete
      @page_template = Cavy::PageTemplate.find(params[:id])
      @page_template.remove_field(params[:field])

      redirect_to admin_edit_page_template_path(@page_template.id), flash: {ssuccess: 'Page Template field was deleted.'}
    end

    private

    def page_template_params
      params.require(:page_template).permit(:name, :type)
    end

  end
end

app/views/layouts/cavy/_admin_header.html.erb
<div class="top-bar">

  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">
        <%= Cavy.title || 'Cavy' %>
      </li>
    </ul>
  </div>

  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <%= render 'cavy/shared/admin_locale_links' %>
      </li>
      <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-user" aria-hidden="true"></i>
              <%= current_user.name %>
            </a>
            <ul class="menu vertical">
              <li>
                <a href="<%= admin_destroy_session_path %>" id="log-out">
                  <i class="fa fa-sign-out" aria-hidden="true"></i>
                  Sign Out
                </a>
              </li>
            </ul>
          </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/layouts/cavy/_admin_sidebar.html.erb
<ul>
  <li>
    <a href="<%= admin_dashboard_path %>" id="admin-overview">
      <i class="fa fa-tachometer" aria-hidden="true"></i>
      Dashboard
    </a>
  </li>
  <li>
    <a href="<%= admin_page_templates_path %>" id="admin-page-templates">
      <i class="fa fa-clipboard" aria-hidden="true"></i>
      Page Templates
    </a>
  </li>

  <li>
    <a href="<%= admin_pages_path %>" id="admin-pages">
      <i class="fa fa-files-o" aria-hidden="true"></i>
      Pages
    </a>
  </li>
  <% Cavy::ItemSection.all.each do |section| %>
      <li>
        <%= link_to section.title, cavy_item_section_path(section.id) %>
      </li>
  <% end %>
  <% if current_user and current_user.role == 'admin' %>
      <li>
        <a href="<%= item_groups_path %>" id="admin-item-groups">
          <i class="fa fa-database" aria-hidden="true"></i>
          Item Groups
        </a>
      </li>
      <% if current_user&.site_manager? %>
          <li>
            <a href="<%= cavy_admin_users_path %>" id="admin-users">
              <i class="fa fa-users" aria-hidden="true"></i>
              Users
            </a>
          </li>
      <% end %>
  <% end %>
</ul>

app/views/layouts/cavy/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <button class="navbar-toggle" data-target=".bs-navbar-collapse" data-toggle="collapse" type="button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= admin_dashboard_path %>">
      <%= Cavy.title || 'Cavy' %>
    </a>
    <div class="nav-collapse collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <% Cavy::Page.all.each do |page| %>
            <li>
              <%= cavy_page(page.route, page.localized_title, id: page.localized_title) %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/cavy/admin_layout.html.erb
<!doctype html>

<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">

  <title><%= @title ? @title : 'Cavy' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <%= stylesheet_link_tag 'cavy/application', media: 'all' %>
  <%= javascript_include_tag 'cavy/application' %>
  <script src="/assets/cavy/ckeditor/ckeditor.js"></script>
  <%= csrf_meta_tags %>
</head>
<body id="site">

<header>
  <%= render 'layouts/cavy/admin_header' %>
</header>

<main id="content">
  <div class="expanded row" id="contentRow">
    <div class="large-2 columns" id="sidebar">
      <%= render 'layouts/cavy/admin_sidebar' %>
    </div>
    <div class="large-10 columns">
      <% flash.each do |key, value| %>
          <div class="callout <%= key %>" style="margin-top: 1em;" data-closable>
            <%= value %>

            <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</main>

<footer>
  &copy; Ruby Rainbows <%= Time.now.year %>
</footer>

</body>
</html>

app/views/layouts/cavy/application.html.erb
<!doctype html>

<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">

  <title><%= @title ? @title : 'Cavy' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <%= stylesheet_link_tag 'cavy/application', media: 'all' %>
  <%= javascript_include_tag 'cavy/application' %>
  <%= csrf_meta_tags %>
  <% unless @page.nil?  %>
      <%= meta_tags(@page) %>
  <% end %>

</head>

<body>
<%= render 'layouts/cavy/header' %>

<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <footer>

      <% if can_edit? && @page %>
          <%= link_to 'edit', admin_edit_page_path(@page.id) %>
      <% end %>
      <%= debug(params) if Rails.env.development? %>

      <br/>

      &copy; Ruby Rainbows <%= Time.now.year %>
    </footer>

  </div>
</div>
</body>
</html>

app/views/layouts/cavy/first_time.html.erb
<!doctype html>

<html lang="<%= I18n.locale %>">

<head>
  <meta charset="utf-8">
  <title><%= @title ? @title : 'Cavy' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag 'cavy/application', media: 'all' %>
  <%= javascript_include_tag 'cavy/application' %>
  <%= csrf_meta_tags %>
</head>

<body id="site">

<header></header>

<main id="centeredContent">
  <%= yield %>
</main>

<footer>
  &copy; Ruby Rainbows <%= Time.now.year %>
</footer>

</body>
</html>

app/views/layouts/cavy/sessions.html.erb
<!doctype html>

<html lang="<%= I18n.locale %>">

<head>
  <meta charset="utf-8">
  <title><%= @title ? @title : 'Cavy' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag 'cavy/application', media: 'all' %>
  <%= javascript_include_tag 'cavy/application' %>
  <%= csrf_meta_tags %>
</head>

<body id="site">

<header>
  <% flash.each do |key, value| %>
      <div class="callout secondary <%= key %>"><%= value %></div>
  <% end %>
</header>

<main id="centeredContent">
  <%= yield %>
</main>

<footer>
  &copy; Ruby Rainbows <%= Time.now.year %>
</footer>

</body>
</html>